env:
  browser: true
  es2021: true
extends: xo
overrides:
  - extends:
      - xo-typescript
      - prettier
    files:
      - '*.ts'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
